[package]
name = "qu6101a2-mon"
version = "1.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
color-eyre = "0.6"
crossterm = "0.29"
ratatui = "0.30"
serialport = "4.8"

[lints.clippy]
all = "warn"
pedantic = "warn"
